### ISSUE TITLE
Trainer/Greeter Dissapear on reload

### ISSUE THREAD

**Issue by CBacchus** [Jessy1237/DwarfCraft_premerge#1]
All trainers and greeters dissapear from the game when i do /reload

**Comment by Jessy1237** [comment]
Well do they come back or do they dissapear until next server restart?

**Comment by CBacchus** [comment]
They do not come back at all they are gone until I do the commands to put them all back one by one

**Comment by CBacchus** [comment]
when i updated to the newest version it fixed :)
