### ISSUE TITLE
Creating Trainer problems

### ISSUE THREAD

**Issue by Genoay** [Jessy1237/DwarfCraft_premerge#13]
Hi,
We are building a Dwarfcraft server and all has been going well initially. Have the latest version installed. We have a training hall at spawn with all 50 trainers permanently created and no problems. We then created only the specialist trainers for each race at their training hall. I used a unique ID for each duplicate trainer, a different name for each duplicate trainer and even different skill ranges for duplicate trainers. The only duplicate is the skill ID or name. All trainers created no problems until the server was restarted and then all the duplicates disappeared even though they are still in the database. Is there some limitation I have missed? Thanks

**Comment by Jessy1237** [comment]
Hmmm thats odd, i'll look into that.

**Comment by Jessy1237** [comment]
Try putting the debug threshold level of dwarfcraft under 5 and tell me does the console say all the trainers are being spawned on server start? There is a setting for it in the plugin config.

**Comment by Jessy1237** [comment]
Hmm well i can't seem to replicate this issue that you have, i have tried it with the skill id of 5 and made 3 trainers, two of them are in the same chunk and one of them is 2 or so chunks away and on server restart they all spawn properly. What plugins are you running? I'm running the latest version of DwarfCraft and Spigot with the bare requirements to run Dwarfcraft.

**Comment by Genoay** [comment]
I have attached some piccys of the server start log file. With the duplicates I get a Java duplicate null pointer exception. Unfortunately the files didn't attach in order but you will get the idea. The debug level was 7 and I reduced it to 4, but no change. As you will see from the log I am running CraftBukkit, the latest Dwarfcraft, PEX, World Edit etc. and all works fine without the duplicate trainers. It does create one duplicate successfully!! Thanks for your help, I have run out of ideas, we will run with just a central training area if we have to but it is a bit of a hassle. Thanks again.

![final_load_msg](https://cloud.githubusercontent.com/assets/10723674/8898502/7f326c40-3468-11e5-822c-3b6b0dd3d296.gif)
![java_warning](https://cloud.githubusercontent.com/assets/10723674/8898503/7f3dfbdc-3468-11e5-9984-75b6ae596836.gif)
![server_versions](https://cloud.githubusercontent.com/assets/10723674/8898504/7f4ab0de-3468-11e5-8494-cb0378545d3f.gif)
![trainer_load](https://cloud.githubusercontent.com/assets/10723674/8898505/7f5780a2-3468-11e5-8e34-1a3f524174a6.gif)

**Comment by Genoay** [comment]
Pressed the wrong button

**Comment by Jessy1237** [comment]
Well DwarfCraft is now built against Spigot because as far as i know craftbukkit fell out due to legal reasons of when mojang took over it. So try running the latest version of DwarfCraft with the latest version of Spigot. Also DwarfCraft isn't backwards compatible either.

**Comment by Genoay** [comment]
I was under the impression that Spigot branched off with Spigot and Craftbukkit from Bukkit which is the one you were referring to. In any case I have installed the latest spigot and updated Citizens however the result is exactly the same with the warning messages. I have assumed the problem is duplicates, the other option I guess is quantity. In the database I have 73 Trainers and 5 Greeters. As the Greeters are the last created and have no problems I assumed it must be a duplicate problem with the Trainers. The log says it loaded 52 NPC's which is the original 50 Trainers and 2 duplicates and then no more even though it loads all 5 Greeters. I now have several versions of the database with different combinations but none have produced any more than each other.
Remember, I created the original 50 in one sitting, then the next night I created the rest and while I didn't test them that night, all appeared OK and they didn't disappear and I didn't notice any error messages. It was only after I shutdown the server and restarted it next day that they had disappeared. Even now if I delete the extras out of the database the error messages disappear.

**Comment by Jessy1237** [comment]
hmmmm thats odd, i'll copy/paste some trainers in my database and get over this 50 limit. Try deleting down to 49 and then make some more. mby citizens is limiting the npcs but i doubt it.

**Comment by Jessy1237** [comment]
Hmmm well i got 60 trainers in and they all loaded up fine and majority are duplicates on the skill level of 5 and with the same name, while others and just normal duplicates with the same names. They all seemed to spawn in fine. What plugins are u running?

**Comment by Jessy1237** [comment]
so i read a little more into the code and it seems like your issue is something to do with the held items of the trainers. So one of the trainers items is missing or has the wrong id. Do you know which trainer isn't spawning?

**Comment by Genoay** [comment]
Jessy, sorry for not getting back to you sooner, been very preoccupied with medical problems. I checked database copies and all were the same. I made a new db and it works now so far, so all is good, and thanks for your help.
