### ISSUE TITLE
Incorrect Item References

### ISSUE THREAD

**Issue by drekryan** [Jessy1237/DwarfCraft_premerge#16]
Multiple Trainers hold or require incorrect items.
1. Mob Hunter asks for sulfur which should be gunpowder. Sulfur doesn't exist but this trainer is correct and will accept gunpowder however the wording is incorrect.
2. The alchemist asks for nether stalk which should be "Nether Wart"
3. The torch maker requires cake to level. This doesnt make logical sense. This maybe should be coal instead?
4. The torch maker holds a Golden Apple instead of a torch.
5. The sign maker holds a sword instead of a sign.

**Comment by Jessy1237** [comment]
You can change the items required for levels skills and the item held by the trainers in the csv files. There are tutorials on the spigot page. I can however fix the name of the items as they have changed over time.

**Comment by drekryan** [comment]
Ok thanks. I still get incorrect wording when clicking the Trainers. Can this be fixed on both the Alchemist and the Mob Hunter?

**Comment by Jessy1237** [comment]
Ok I'll look into it further after uni

**Comment by Jessy1237** [comment]
Fixed all these issues in the latest version. For these fixes to take place you will have to delete your .csv files in DwarfCrafts plugin Folder so they can be reset by the plugin.
