### ISSUE TITLE
Oak Wood Metadata Issue

### ISSUE THREAD

**Issue by drekryan** [Jessy1237/DwarfCraft_premerge#18]
I am running into a metadata issue with DwarfCraft. I tried this in pure vanilla and pure Spigot and only started running into this issue after adding the DwarfCraft plugin.

If you stack three vertical oak logs and then place a horizontal oak log on the side. Next break all these logs in survival. When breaking the horizontal log you will get a broken texture log and this will occasionally be named as "Acacia Wood" for some strange reason.

These logs can be fixed by restacking them vertically and breaking them but it is a waste of durability on tools to have to fix them.

**Comment by Jessy1237** [comment]
Hmm ok my fix for this bug must have died, i'll have to find another one. This happens bc there are 4 data points for every log type and to drop extra logs we have to set it to the vertical log metadata first otherwise you get horizontal logs which is bad. So this should be an easy fix.

**Comment by Jessy1237** [comment]
Apparently idk who either Mojang or the Spigot team fixed the issue in their code so my old fix for this problem was actually breaking the metadata. It is now fixed in the latest version.
