### ISSUE TITLE
Birch, Spruce, and Jungle Wood gives Oak Wood

### ISSUE THREAD

**Issue by drekryan** [Jessy1237/DwarfCraft_premerge#19]
This issue was caused by the following commit
https://github.com/Jessy1237/DwarfCraft/commit/42fafb6a2dde82ec3088a0cf5a0c6e86fdf65e9c

The mentioned commit fixed the issue with horizontal oak wood missing texture and metadata issues but it now also causes all Spruce, Birch, and Jungle Logs to give Oak Logs when broken.

This makes it impossible to get Spruce, Birch, and Jungle Wood in the world.

Label: [Major Bug]

**Comment by Jessy1237** [comment]
Yep all good finally figured out, metadata is pretty much dead so i send the metadata to the durability of the new item.
