### ISSUE TITLE
Races reset after relog

### ISSUE THREAD

**Issue by ghost** [Jessy1237/DwarfCraft_premerge#2]
When you choose a race using /race elf confirm and then, relog, you do /race , it says "You are a Dwarf" Please help!

**Comment by Jessy1237** [comment]
Okay i found the problem was missing a line of code, this will be fixed in the next update.

**Comment by ghost** [comment]
Not to be pushy but, can you make sure custom races also don't reset and hurry up w/ the update? Thanks!

**Comment by Jessy1237** [comment]
what do you mean custom races reset, i know when you change your race it resets. I fixed that but what is this new error.

**Comment by ghost** [comment]
It's not a new error, but when you make your own races... let's say:
Terran: [insert skill numbers here]
And... could you make sure that if you do /race Terran confirm it'd be fine
with it?
Thanks for your patience!

On Sun, Jun 2, 2013 at 8:33 PM, Jessy1237 notifications@github.com wrote:

> what do you mean custom races reset, i know when you change your race it
> resets. I fixed that but what is this new error.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Jessy1237/DwarfCraft/issues/2#issuecomment-18820551
> .

## 

--Ian

**Comment by Jessy1237** [comment]
Ohhh ok yer thats already fixed. I'll be releasing hopefully a an update with npc movement as in pathing for walking too.
