### ISSUE TITLE
Major Shift-Clicking Crafting Issue

### ISSUE THREAD

**Issue by drekryan** [Jessy1237/DwarfCraft_premerge#22]
With the enabling of shift-clicking again this has caused a major gameplay issue on our server. We have downgraded DwarfCraft in the meantime.

When shift-clicking in crafting it ignores your DwarfCraft levels.
For example I took a stack of coal and a stack of sticks. 

Crafting this by shift-clicking gives me 4 stacks of torches (which is vanilla) crafting. I am only level 1 Torch Maker.

Crafting this manually with one stack of coal and one stack of sticks without shift-clicking performs the craft the way it should for my level and only gives me about one stack of torches.

**Comment by Jessy1237** [comment]
Should be fixed in the latest version. Once its out.
