### ISSUE TITLE
Ore Miner Skill

### ISSUE THREAD

**Issue by drekryan** [Jessy1237/DwarfCraft_premerge#23]
Version 2.2 of DwarfCraft added ore drops in addition to auto smelted ingots. But this also caused players with level 0 Ore Miner to have a 0.00% chance of getting coal from mining coal ore. This makes it impossible to get the coal needed to level up unless another player with a higher level can give you coal.

**Comment by Jessy1237** [comment]
This was fixed in 2.3.1 :P
