### ISSUE TITLE
Ongoing Trainer Issues

### ISSUE THREAD

**Issue by Genoay** [Jessy1237/DwarfCraft_premerge#25]
Jessy1237, my apologies for not replying to the last issue but some serious medical problems have taken all my time.
I read your last message about the trainers holding the wrong item. My question is where is the reference file I can use to check the database against. I created another database with the original 50 trainers and just the extra 12 trainers for the Human race.
I stripped down the server to be running the latest versions of Spigot, Dwarfcraft, Citizens and Vault only. I created all 62 trainers in one sitting, all seemed OK, I could log off and back on and all was still OK, I restarted the server and up came the Java error messages. Logging on and all original 50 trainers are there but only 1, the first in the database, of the Humans. I have changed the order of the Humans and it still picks the first to display and ignores the rest.

Now the issue with the held items, on checking the database there appeared to be some strange entries, but they were the same as the earlier databases. For example the melon farmer is listed as having material 0, and the swordsman and the signmaker both have 267.
I have opened the Skills.csv file and compared the database against the Item 1 column and there are many differences so I don't know what should be in the database or if there is somewhere else I should be looking.
Thanks Genoay

**Comment by Jessy1237** [comment]
What version of dwarfcraft are you currently running? As apart from you i have never encountered this kind of issue before.

**Comment by Jessy1237** [comment]
As apart from you i have never encountered this kind of issue before.

**Comment by Genoay** [comment]
2.1.2

**Comment by Jessy1237** [comment]
So you've got 2.1.2 DwarfCraft and spigot for Minecraft 1.8.3? If you have anything past 1.8.3 DwarfCraft wont run as its not backwards compatible as it relies on classes in the Net Minecraft Server source inside of spigot, which changes branch name every new version of minecraft, hence no backwards/forwards compatibility. So if you run DwarfCraft 2.5.9 with Spigot for Minecraft 1.8.8 then it will work fine. However i believe your database has become corrupt become of these compatibility issues so you will also need to reset that. Tell me how it runs after that.

**Comment by Genoay** [comment]
I have now got Dwarfcraft 2.5.9 and I already had Spigot for Minecraft 1.8.8. I deleted the database and dwarfcraft folder in plugins and re-created all the trainers, 50 original and 12 Humans. The result is the same with only the first human remaining visible. Below are the console messages.

8:49:00 PM [WARN] java.lang.NullPointerException
8:49:00 PM [WARN]   at com.Jessy1237.DwarfCraft.DwarfTrainer.<init>(DwarfTrainer.java:104)
8:49:00 PM [WARN]   at com.Jessy1237.DwarfCraft.DataManager.populateTrainers(DataManager.java:541)
8:49:00 PM [WARN]   at com.Jessy1237.DwarfCraft.DataManager.<init>(DataManager.java:47)
8:49:00 PM [WARN]   at com.Jessy1237.DwarfCraft.DwarfCraft.onEnable(DwarfCraft.java:299)
8:49:00 PM [WARN]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
8:49:00 PM [WARN]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
8:49:00 PM [WARN]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
8:49:00 PM [WARN]   at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
8:49:00 PM [WARN]   at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
8:49:00 PM [WARN]   at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
8:49:00 PM [WARN]   at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
8:49:00 PM [WARN]   at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
8:49:00 PM [WARN]   at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
8:49:00 PM [WARN]   at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
8:49:00 PM [WARN]   at java.lang.Thread.run(Unknown Source)

**Comment by Jessy1237** [comment]
Try deleting your effect.csv and skills.csv and then restarting the server that may fix it. I have a feeling it's been edited.

**Comment by Genoay** [comment]
Tried deleting, no different.
I have discovered a clue, it means nothing to me but I am hoping it means something to you.
If I have done everything as you have asked the only differences between our 2 servers should be the locations of the duplicate trainers so I created the Human trainers within view of the originals and EUREKA, it works.
On my server, spawn is at 0.70.0 and each race is located ~4,000 blocks NSEW of spawn so e.g.  N and S are 8,000 blocks apart.

**Comment by drekryan** [comment]
Would there be maybe a way you could ZIP up your DwarfCraft data folder and paste a download link here for it so we can take a look?

**Comment by Genoay** [comment]
https://drive.google.com/file/d/0B_gAJ9RH6HYlNDFKa3JPR1ByN0k/view?usp=sharing

**Comment by Genoay** [comment]
At 100 blocks away all is good but at 200 blocks all but the first Human disappear.

**Comment by Jessy1237** [comment]
Try updating your citizens and see if that works. You might have to update to the latest dev build.

**Comment by Genoay** [comment]
No change with citizens 2.0.16-SNAPSHOT (build 1247)

**Comment by Genoay** [comment]
Jessy1237, if you are confident there is nothing in Dwarfcraft that is location dependent I am going to regen the world and see what happens. We aren't making any progress atm and as much as I hate to start again it is the only thing I can think of.

**Comment by Genoay** [comment]
Also there won't be any responses from me next week (from Monday) as I will be in hospital. Should be home on the weekend.

**Comment by Jessy1237** [comment]
Well i've never come across this kind of issue before. Try a complete refresh, spigot and all the plugins included. With new world and everything. See what happens then if it still happens then i don't know whats happening.

**Comment by Genoay** [comment]
Tried all that, new world also, same result. What is the relationship with Citizens, are the Trainers meant to be recorded in the citizens save.yml also? They don't on mine but what does happen is the first of the duplicate trainers is recorded in save.yml as part of the server shutdown the first time after creating it. I hadn't been checking this before so never noticed.

**Comment by Jessy1237** [comment]
There shouldn't be any dwarfcraft npc's saved in the citizens save.yml as dwarfcraft despawns all npcs when the plugin is disabled (i.e. server shutdown/reload) however i did run a citizens save and saved all the npcs to file, then i stop and started the server and it removed everything from the citizens save. So i did the same as before except i copied the citizens save and put it back in before i restarted the server so that when i started the server it had all the npcs saved with citizens and all 71 of my npcs still loaded up just fine.

**Comment by Genoay** [comment]
Well I think you may as well close this issue unless you have anything else to try. I'm not giving up on Dwarfcraft yet but it isn't going to be something simple.
What I plan on doing is a lot of reading on Minecraft to see what I can discover. I copied the server to a thumb drive and tried it on my son's computer and got the same result.
I have changed the server from Bukkitt to Spigot, deleted Minecraft and re-installed, deleted the mods and re-downloaded them all, generated a new world, for exactly the same result I got at the beginning.
Thanks for your help, if I find the solution I'll open another issue to tell you.
Thanks Genoay

**Comment by Jessy1237** [comment]
Cheers
