### ISSUE TITLE
Dwarfcraft working

### ISSUE THREAD

**Issue by Genoay** [Jessy1237/DwarfCraft_premerge#35]
Jessy1237, 
I have installed your latest version and it works as intended, no problems with Trainers. One question though, how do you configure the Greeters to speak now they are all saved in Citizens instead?
We have been testing the server for the last 4 weeks and are getting close to "GoLive"
Thank you for all your help.
Genoay

**Comment by Jessy1237** [comment]
You have two messages one for right click and one for left click. These can be set with a messageID in the greeters.config. Also please post any issues in the other DwarfCraft repo as this is a deprecated repo before the merge with LexManos's repo.
