### ISSUE TITLE
Min level suggestion

### ISSUE THREAD

**Issue by Deimos161** [Jessy1237/DwarfCraft_premerge#4]
Hey bud.

Are you able to implement a min level for trainers?
Meaning we can set a max level for trainers. That way I could set trainers to a max of level 15 in one area and then in another I could set it so they are level 16-30.

**Comment by Jessy1237** [comment]
Yes that shouldn't be too hard, however the dwarfcraft.db file may need to be reset if i can't get the trainer data to be converted to the new format with the min level.

**Comment by Deimos161** [comment]
No problems, How long do you think it would take you to put this in? I only ask because I'm opening my server at 9am this coming friday.

**Comment by Deimos161** [comment]
Does this mean that min levels are in now?

**Comment by Jessy1237** [comment]
Yup

**Comment by Deimos161** [comment]
Hey Jessy,

How do I set a min level?
I finally updated to 1.6.4 :P
