### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by rowlandan25** [Jessy1237/DwarfCraft_premerge#8]
When I install DwarfCraft, everything works great until I restart the server.  I am able to add new trainers, greeters, and players are able to interact with those npc's.  However, when I restart the server, the server crashes seconds after finishing loading.  I have attached a picture of the server log for one start after DwarfCraft has been installed.  

During the server start-up, I get a WARNING from DC stating "NPC with that id already exists, existing NPC returned".  I get one of these messages for every NPC that I have created.  After the server starts up, I get a Java Exception for:

2013-10-24 11:31:36 [SEVERE] "Silently" catching entity tracking error.
2013-10-24 11:31:36 [SEVERE] net.minecraft.server.v1_6_R3.ReportedException: Adding entity to track

Then a bunch more follow that.

![npcerror-1](https://f.cloud.github.com/assets/1084662/1400753/4aa69ea2-3cca-11e3-9f42-7f930e8bc3ba.JPG)
![npcerror-3](https://f.cloud.github.com/assets/1084662/1400754/4aa7f61c-3cca-11e3-9039-5d2702874942.JPG)
![npcerror-2](https://f.cloud.github.com/assets/1084662/1400755/4aa87a38-3cca-11e3-9d33-23722a9b28b9.JPG)

If you want a copy of the server log with all of the errors, let me know and I can email them to you.  This error is not present if I delete the DwarfCraft folder from the plugins folder or if I remove the DC jar from the plugins folder.

The server has the following specs:

Ubuntu 12.04.3 LTS on a Virtual Host (8 GB RAM)
Newest Bukkit Recommended release (1.6.4-R1.0)

It is running the following plugins:
  Dynamic Effect Whitelist (v1.5.2)
  Essentials (v.2.12.1)
  mcore (v.6.8.1)
  Factions (v2.2.1)
  Group Manager (v2.10.1)
  Mobile Admin (v3.2.4)
  PlayerLogger (v.2.9.1)
  Vault (v1.2.27-b349)
  WorldEdit (v5.5.8)

I still received the error when I was only running Essentials, GroupManager, and Vault.  Like I said before, if I move the .jar file for DwarfCraft out of the plugins folder, the server is able to start up just fine.

Update:
If I let all the java errors go through (and they eventually) stop, the server will continue to run.  I have not seen these errors occur after the server is started.

**Comment by Jessy1237** [comment]
Don't worry about the warning about entity already existing thats meant to happen when its converting the trainer database because its re-creating the trainers so when it tries to make the npcs it already exists for that trainer so bukkit returns that entity. However its not meant to convert the trainer table every restart. I did fix that though.
